/**
 * Minimal, dependency-free PDF generator for invoices.
 *
 * jsPDF is in package.json but pulling it client-side adds ~100kb. Instead
 * we ship a tiny PDF writer that produces a clean, single-page A4 invoice
 * with company branding, line items and totals. Output is a Blob the
 * browser can download directly.
 */

import { formatCurrency, formatDate } from "@/lib/format";
import { nova } from "@/config/nova";
import type { Invoice, InvoiceItem } from "@/types/database";

interface BuildArgs {
  invoice: Invoice;
  items: InvoiceItem[];
  company: {
    name: string;
    currency: string;
    industry?: string | null;
    timezone?: string | null;
  };
  clientLabel?: string | null;
}

/**
 * The PDF format is straightforward: write a few content streams, position
 * text by absolute coordinates (1pt = 1/72 inch), embed Helvetica.
 */
export function buildInvoicePdf(args: BuildArgs): Blob {
  const { invoice, items, company, clientLabel } = args;

  const lines: string[] = [];
  const W = 595; // A4 width in pt
  const H = 842; // A4 height in pt
  const M = 56;

  function add(line: string) {
    lines.push(line);
  }

  // --- Header bar
  add(`q 0.27 0.37 1 rg ${0} ${H - 80} ${W} 80 re f Q`);
  add(`q 1 1 1 rg`);
  add(`BT /F2 22 Tf ${M} ${H - 50} Td (${esc(nova.name)}) Tj ET`);
  add(`BT /F1 11 Tf ${M} ${H - 70} Td (${esc("Invoice")}) Tj ET`);
  add(
    `BT /F1 11 Tf ${W - M - 100} ${H - 50} Td (${esc(
      "#" + invoice.number
    )}) Tj ET`
  );
  add(
    `BT /F1 9 Tf ${W - M - 100} ${H - 65} Td (${esc(
      formatDate(invoice.issue_date)
    )}) Tj ET`
  );
  add(`Q`);

  // --- From / To
  let y = H - 130;
  add(`BT /F2 11 Tf ${M} ${y} Td (${esc("From")}) Tj ET`);
  y -= 16;
  add(`BT /F1 11 Tf ${M} ${y} Td (${esc(company.name)}) Tj ET`);

  y = H - 130;
  const toX = W / 2 + 20;
  add(`BT /F2 11 Tf ${toX} ${y} Td (${esc("Bill to")}) Tj ET`);
  y -= 16;
  add(
    `BT /F1 11 Tf ${toX} ${y} Td (${esc(clientLabel || "Customer")}) Tj ET`
  );

  // --- Status pill
  add(
    `q 0.96 0.96 0.97 rg ${W - M - 80} ${H - 130 + 4} 80 22 re f Q`
  );
  add(
    `BT /F2 9 Tf ${W - M - 70} ${H - 130 + 18} Td (${esc(
      invoice.status.toUpperCase()
    )}) Tj ET`
  );

  // --- Items table header
  y = H - 220;
  const colDescX = M;
  const colQtyX = W - M - 240;
  const colPriceX = W - M - 160;
  const colAmountX = W - M - 60;

  add(`q 0.92 0.93 0.96 rg ${M} ${y - 6} ${W - 2 * M} 24 re f Q`);
  add(`BT /F2 10 Tf ${colDescX + 8} ${y + 6} Td (${esc("Description")}) Tj ET`);
  add(`BT /F2 10 Tf ${colQtyX} ${y + 6} Td (${esc("Qty")}) Tj ET`);
  add(`BT /F2 10 Tf ${colPriceX} ${y + 6} Td (${esc("Unit price")}) Tj ET`);
  add(
    `BT /F2 10 Tf ${colAmountX - 30} ${y + 6} Td (${esc("Amount")}) Tj ET`
  );

  // --- Items
  y -= 28;
  for (const it of items) {
    if (y < 140) break;
    add(
      `BT /F1 10 Tf ${colDescX + 8} ${y} Td (${esc(it.description)}) Tj ET`
    );
    add(
      `BT /F1 10 Tf ${colQtyX} ${y} Td (${esc(String(it.quantity))}) Tj ET`
    );
    add(
      `BT /F1 10 Tf ${colPriceX} ${y} Td (${esc(
        formatCurrency(it.unit_price, company.currency)
      )}) Tj ET`
    );
    add(
      `BT /F1 10 Tf ${colAmountX - 30} ${y} Td (${esc(
        formatCurrency(it.amount, company.currency)
      )}) Tj ET`
    );
    y -= 22;
  }

  // --- Totals box
  const boxX = W - M - 230;
  const boxY = 110;
  add(`q 0.96 0.96 0.97 rg ${boxX} ${boxY} 230 90 re f Q`);
  add(
    `BT /F1 10 Tf ${boxX + 12} ${boxY + 70} Td (${esc("Subtotal")}) Tj ET`
  );
  add(
    `BT /F1 10 Tf ${boxX + 130} ${boxY + 70} Td (${esc(
      formatCurrency(invoice.subtotal, company.currency)
    )}) Tj ET`
  );
  add(
    `BT /F1 10 Tf ${boxX + 12} ${boxY + 50} Td (${esc(
      `Tax (${invoice.tax_rate}%)`
    )}) Tj ET`
  );
  add(
    `BT /F1 10 Tf ${boxX + 130} ${boxY + 50} Td (${esc(
      formatCurrency(invoice.tax_amount, company.currency)
    )}) Tj ET`
  );
  add(
    `BT /F2 12 Tf ${boxX + 12} ${boxY + 24} Td (${esc("Total")}) Tj ET`
  );
  add(
    `BT /F2 12 Tf ${boxX + 130} ${boxY + 24} Td (${esc(
      formatCurrency(invoice.total, company.currency)
    )}) Tj ET`
  );

  // --- Notes
  if (invoice.notes) {
    add(`BT /F1 9 Tf ${M} 90 Td (${esc("Notes")}) Tj ET`);
    add(
      `BT /F1 9 Tf ${M} 76 Td (${esc(invoice.notes.slice(0, 110))}) Tj ET`
    );
  }

  // --- Footer
  add(
    `BT /F1 8 Tf ${M} 50 Td (${esc(
      `Generated by ${nova.name} · ${formatDate(invoice.issue_date)}`
    )}) Tj ET`
  );

  return assemblePdf(lines.join("\n"));
}

function esc(s: string) {
  return String(s)
    .replace(/\\/g, "\\\\")
    .replace(/\(/g, "\\(")
    .replace(/\)/g, "\\)")
    .replace(/[\r\n]/g, " ");
}

function assemblePdf(content: string): Blob {
  const objects: string[] = [];
  const xrefOffsets: number[] = [];

  function addObj(body: string) {
    const idx = objects.length + 1;
    objects.push(`${idx} 0 obj\n${body}\nendobj`);
    return idx;
  }

  // 1: catalog → 2: pages → 3: page → 4: contents → 5,6: fonts
  const fontHelvetica = addObj(
    `<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>`
  );
  const fontHelveticaBold = addObj(
    `<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>`
  );
  const contents = addObj(
    `<< /Length ${content.length} >>\nstream\n${content}\nendstream`
  );
  const page = addObj(
    `<< /Type /Page /Parent 0 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 ${fontHelvetica} 0 R /F2 ${fontHelveticaBold} 0 R >> >> /Contents ${contents} 0 R >>`
  );
  const pages = addObj(
    `<< /Type /Pages /Kids [${page} 0 R] /Count 1 >>`
  );
  const catalog = addObj(`<< /Type /Catalog /Pages ${pages} 0 R >>`);

  // patch page parent ref
  objects[page - 1] = objects[page - 1].replace(
    "/Parent 0 0 R",
    `/Parent ${pages} 0 R`
  );

  // assemble
  let body = "%PDF-1.4\n%\u00E2\u00E3\u00CF\u00D3\n";
  for (const obj of objects) {
    xrefOffsets.push(body.length);
    body += obj + "\n";
  }
  const xrefPos = body.length;
  body += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const off of xrefOffsets) {
    body += `${String(off).padStart(10, "0")} 00000 n \n`;
  }
  body += `trailer\n<< /Size ${
    objects.length + 1
  } /Root ${catalog} 0 R >>\nstartxref\n${xrefPos}\n%%EOF`;

  return new Blob([body], { type: "application/pdf" });
}

export function downloadInvoicePdf(args: BuildArgs) {
  const blob = buildInvoicePdf(args);
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `invoice-${args.invoice.number}.pdf`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
